// 待删
let Dic_Data = {
    'ALLL_DIC_CODE': [
        {
            'id':'ill_reason',
            'text':'疾病原因(ill_reason)'
        }, {
            'id':'operation_log_level',
            'text':'操作日志级别(operation_log_level)'
        }, {
            'id':'goods_status',
            'text':'商品状态(goods_status)'
        }, {
            'id':'PROJECT_TYPE',
            'text':'PROJECT_TYPE(项目类型)'
        }
    ],
    'COMMON_YES_OR_NO':[
        {
            'id':'0',
            'text':'否'
        },
        {
            'id':'1',
            'text':'是'
        }
    ],
    'MODULE_SEARCH_TYPE':[
        {
            'id':'1',
            'text':'数据字典'
        },
        {
            'id':'2',
            'text':'自定义'
        }
    ],
    'SHOW_TYPE':[
        {
            'id':'text',
            'text':'文本'
        },
        {
            'id':'dic',
            'text':'数据字典值'
        },
        {
            'id':'date',
            'text':'日期'
        },
        {
            'id':'dateTime',
            'text':'时间'
        },
        {
            'id':'money',
            'text':'金额'
        },
        {
            'id':'percent',
            'text':'百分比'
        },
        {
            'id':'imgSingle',
            'text':'单图'
        },
        {
            'id':'img',
            'text':'多图片'
        },
        {
            'id':'minute',
            'text':'时间(精确到分钟)'
        },
        {
            'id':'richText',
            'text':'富文本'
        },
        {
            'id':'count',
            'text':'关联表记录数'
        },
        {
            'id':'linkModule',
            'text':'模型关联字段'
        },
        {
            'id':'colorPicker',
            'text':'颜色'
        },
        {
            'id':'code',
            'text':'代码块'
        },
        {
            'id':'attach',
            'text':'单附件'
        },
        {
            'id':'attachMulti',
            'text':'多附件'
        },
        {
            'id':'attachList',
            'text':'多附件-列表'
        }
    ],
    'MODULE_VALIDATION_RULE_SELECT':[
        {
            'id':'unique',
            'text':'唯一'
        },
        {
            'id':'required',
            'text':'必填'
        },
        {
            'id':'numeric',
            'text':'整数'
        },
        {
            'id':'decimal',
            'text':'小数'
        },
        {
            'id':'num',
            'text':'数字'
        },
        {
            'id':'decimal=2',
            'text':'小数-保留2位'
        },
        {
            'id':'email',
            'text':'邮箱'
        },
        {
            'id':'mobileNum',
            'text':'手机号码'
        },
        {
            'id':'telephoneNum',
            'text':'座机号码'
        },
        {
            'id':'phoneNum',
            'text':'电话(手+座)'
        },
        {
            'id':'IDCard',
            'text':'身份证'
        }
    ],
    'MODULE_EDIT_SOURCE':[
        {
            'id':'1',
            'text':'数据字典'
        },
        {
            'id':'2',
            'text':'自定义'
        },
        {
            'id':'3',
            'text':'模型'
        }
    ],
    'ADDRESS_TYPE':[
        {
            'id':'600-1-20-600',
            'text':'菜单-单选'
        },
        {
            'id':'600-0-20-600',
            'text':'菜单-多选'
        },
        {
            'id':'2-1-20-2',
            'text':'用户'
        },
        {
            'id':'2-1-0-2',
            'text':'部门'
        },
        {
            'id':'1-1-1-1',
            'text':'抽象集合'
        },
        {
            'id':'64-1-40-64',
            'text':'角色'
        }
    ],
    'OPEN_TYPE':[
        {
            'id':'0',
            'text':'TAB形式'
        },
        {
            'id':'1',
            'text':'新窗口'
        },
        {
            'id':'2',
            'text':'弹出框'
        }
    ],
    'EDIT_TYPE':[
        {
            'id':'text',
            'text':'文本框'
        },
        {
            'id':'int',
            'text':'整数'
        },
        {
            'id':'number',
            'text':'数字'
        },
        {
            'id':'password',
            'text':'密码'
        },
        {
            'id':'readonly',
            'text':'只读文本'
        },
        {
            'id':'disabled',
            'text':'只读文本-不提交'
        },
        {
            'id':'destroyed',
            'text':'不提交文本'
        },
        {
            'id':'textarea',
            'text':'文本域'
        },
        {
            'id':'hidden',
            'text':'隐藏'
        },
        {
            'id':'select',
            'text':'下拉框'
        },
        {
            'id':'checkbox',
            'text':'单复选框'
        },
        {
            'id':'checkboxlist',
            'text':'复选框'
        },
        {
            'id':'radio',
            'text':'单选按钮'
        },
        {
            'id':'date',
            'text':'日期'
        },
        {
            'id':'datetime',
            'text':'时间'
        },
        {
            'id':'dateRange',
            'text':'时间段'
        },
        {
            'id':'year',
            'text':'年'
        },
        {
            'id':'attach',
            'text':'单附件'
        },
        {
            'id':'attachMulti',
            'text':'多附件'
        },
        {
            'id':'imgSingle',
            'text':'单图片'
        },
        {
            'id':'img',
            'text':'多图片'
        },
        {
            'id':'addressbook',
            'text':'地址本'
        },
        {
            'id':'color-single',
            'text':'颜色选择器单选'
        },
        {
            'id':'color-multiple',
            'text':'颜色选择器多选'
        },
        {
            'id':'richText',
            'text':'富文本'
        },
        {
            'id':'switch',
            'text':'开关'
        },
        {
            'id':'code',
            'text':'代码块'
        },
        {
            'id':'addressPicker',
            'text':'地址级联'
        },
        {
            'id':'selectListData',
            'text':'弹出框列表单选'
        },
        {
            'id':'selectListDataMulti',
            'text':'弹出框列表多选'
        },
        {
            'id':'iconPicker',
            'text':'图标选择器'
        },
        {
            'id':'pathPicker',
            'text':'页面选择器'
        },
        {
            'id':'codeMirror',
            'text':'sql编辑器'
        }
    ],
    'SELECTOR_TYPE':[
        {
            'id':'0',
            'text':'下拉多选框'
        },
        {
            'id':'1',
            'text':'模糊搜索框'
        },
        {
            'id':'6',
            'text':'数字区间'
        },
        {
            'id':'5',
            'text':'时间选择器'
        },
        {
            'id':'9',
            'text':'下拉单选框'
        },
        {
            'id':'11',
            'text':'年选择器'
        },
        {
            'id':'12',
            'text':'年月选择器'
        },
        {
            id: '15',
            text: '复选框'
        }
    ]
}

// import { Dic_Data } from '@/service/mockFormDesignerData.js'
export {
    // 数据字典数据
    Dic_Data,
}