#jasypt加密配置
jasypt:
  encryptor:
    password: @maven.jasypt.encryptor.password@ #加密时的salt值
  # springboot-admin配置:
  boot:
    admin:
      client:
        url: http://123456:7890
        instance:
          prefer-ip: true
          # 建议换成实际项目名称
          name: @artifactId@
          service-base-url: http://123456:7890
        enabled: false