spring:
  redis:
    enabled: true
    #Redis数据库索引（默认为0）
    database: @maven.redis.database@
    #Redis服务器地址
    host: @maven.redis.servers@
    #Redis服务器连接端口
    port: @maven.redis.port@
    #Redis服务器连接密码（默认为空）
    password: @maven.redis.password@
    # 连接超时时间（毫秒）
    timeout: 10000
    jedis:
      pool:
        #连接池中的最大空闲连接
        max-idle: 200
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 1024
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        #连接池中的最小空闲连接
        min-idle: 100